### ISSUE TITLE
docs: the query and mutation factory pages have snippets that fail tsc and claims the factories don't match

### ISSUE THREAD

**Issue by b3hr4d** [B3Pay/ic-reactor#694]
The factory reference pages (`reference/factories/*`) contain snippets that fail
`tsc --strict` and notes that describe caching, `select` and suspense behaviour
the factories don't have.

Snippets were type-checked strict with TypeScript 6.0.3 against the built
packages (each page's hypothetical canister is a typed stand-in). Behaviour was
measured with vitest probes: a real `Reactor`, `callMethod` spied.

## Defects

| # | Page:line (origin/main 6c0c8e536) | Problem | Evidence |
| --- | --- | --- | --- |
| 1 | `reference/factories/createQuery.mdx:43-44` | Lists `select` among the options that "apply to the hook only" | The query object applies the config's `select` itself: `fetch()` and `getCacheData()` both returned the selected value (`"Alice"`, not the user record). |
| 2 | `createQuery.mdx:109` | `<h1>{user.name}</h1>` on `useQuery()` data | TS18049 `'user' is possibly 'null' or 'undefined'`. `useQuery()` data includes `undefined` even when a loader has filled the cache. |
| 3 | `createQuery.mdx:274` | `userQuery.setData((old) => ({ ...old, name: "Alice" }))` | TS2345: `old` is `User \| undefined`, so the spread yields `{ name: string; id?: ... }`, which isn't a `User`. |
| 4 | `createQuery.mdx:357-358` | `fetch()` "returns cached data if fresh, or fetches if stale" | It is cache-first. On a stale entry, `fetch()` returned the cached value and made no canister call (`fetch #1: first \| fetch #2 on a stale entry: first \| canister calls: 1`). This is the `fetchQuery` behaviour #596 documented for the Reactor page. |
| 5 | `reference/factories/createSuspenseQuery.mdx:185-192` | "Parallel Suspense Queries": three `useSuspenseQuery()` calls in one component "run in parallel - not waterfall!" | They ran in series: three 150 ms calls started at 3, 157 and 309 ms. Prefetching or one component per query starts them together (0 and 1 ms). |
| 6 | `reference/factories/createSuspenseInfiniteQuery.mdx:35-38` | Says `as const` makes `getArgs` return the argument tuple, without a caveat | `as const` also makes nested arrays readonly. For a method taking `(opt text, nat, nat)`, `[[], cursor, 10n] as const` fails with TS2322 `Type 'readonly []' is not assignable to type '[] \| [string]'`; an `opt` inside a record fails the same way, and a `vec` fails with TS4104. Annotating the return type compiles. The function returned by `createSuspenseInfiniteQueryFactory` needs neither. |
| 7 | `createSuspenseInfiniteQuery.mdx:296-309` | `CategoryPage` calls `query.useSuspenseInfiniteQuery()` and wraps its own output in `<Suspense fallback={<ProductGridSkeleton />}>` | The hook suspends `CategoryPage` itself, so that boundary never renders; the nearest boundary above it shows its fallback. Measured: `fallbacks rendered: ["outer boundary"]`. |
| 8 | `reference/factories/createMutation.mdx:158, 181, 190` | Optimistic-update example calls `getPostQuery(postId)` | `getPostQuery` isn't defined on the page. A query factory (`createQueryFactory`) takes the args tuple: TS2345 `Argument of type 'string' is not assignable to parameter of type '[string]'` on all three lines. |
| 9 | `reference/factories/overview.mdx:183-185` | "A `*Factory` variant takes the args tuple ... calling `getUserQuery(["alice"])` multiple times returns the same object instance" | True for `createQueryFactory` and `createSuspenseQueryFactory`. `createInfiniteQueryFactory` and `createSuspenseInfiniteQueryFactory` take a `getArgs` function and build a new object on every call (measured: same instance `true`, `false`, `false`). |
| 10 | `reference/factories/createInfiniteQuery.mdx:103` | Virtual-scroll example imports `{ useRef, useCallback }` | It never uses `useCallback` and calls `useEffect` (line 145), which isn't imported: TS2304 `Cannot find name 'useEffect'` when the block is compiled on its own. |

## Repro

- Type errors: `scratchpad/site/extract.mjs` pulls every ts/tsx block with its
  page and fence line, `gen.mjs` writes one module per block into
  `scratchpad/site/consumer`, `check.mjs` type-checks them and maps
  diagnostics back to page lines (`check-before.txt` on origin/main).
- #6: `scratchpad/site/consumer/src/typeprobes/infinite-getargs*.tsx` try the
  plain, `as const` and annotated forms on `useReactorInfiniteQuery`,
  `createInfiniteQuery`, `createSuspenseInfiniteQuery`, the factory call and the
  bound hooks.
- Behaviour: `scratchpad/site/consumer/probes/factory-claims.test.tsx`
  (#1, #4, #5, #7, #9), `siblings.test.tsx` (#5, the parallel alternative).

## Why it matters

#4 misleads anyone who calls `fetch()` after a mutation expecting fresh data.
#5 and #7 recommend layouts that don't do what the page says. #2, #3, #6, #8
and #10 are copy-paste failures.

## Fix plan

Branch `docs/site-factories`, docs only: correct the notes (#1, #4, #9), add the
`as const` caveat with an annotated example (#6), restructure the suspense
examples (#5 one component per query; #7 boundary in the parent), and fix the
snippets (#2, #3, #8, #10).

## Acceptance

- [ ] Every code block on the six factory pages type-checks strict against the built packages, apart from signature listings and intentional-error demos.
- [ ] No page says `fetch()` refetches a stale entry or that `select` is hook-only.
- [ ] The parallel-suspense example starts its calls together (probe).
- [ ] The overview tip names which factories cache and which take `getArgs`.
- [ ] The `as const` note says it fails for `opt`/`vec` arguments and shows a form that compiles.
